### ISSUE TITLE
Generator.Client.Desktop "Build template" button always greyed out

### ISSUE THREAD

**Issue by alelom** [taori/Amusoft.VisualStudio.TemplateGenerator#12]
### Description
No matter the configuration:
<img src="https://user-images.githubusercontent.com/6352844/65602615-13b48280-df9c-11e9-852a-037124e06f02.png" width=450>

The button is always greyed out:
<img src="https://user-images.githubusercontent.com/6352844/65602642-1fa04480-df9c-11e9-9a07-41360c3a6dcc.png" width=500>

Also, on config save, when reopening it through the "Edit" button, the output folder is never saved:
<img src="https://user-images.githubusercontent.com/6352844/65602746-51191000-df9c-11e9-8004-cdec129760a3.png" width=450>

### Tested branches
- Master
- Dev

**Comment by alelom** [comment]
Solved by removing the icon paramter, I think

**Comment by taori** [comment]
Thanks for the screenshots. i'll have a look at it. from the screenshots though it looks like this might happen because you did not select an icon type. i hope i did not commit a partial state to master. that would be dumb. At the time i wrote this i was still sort of getting used to the git workflow

**Comment by taori** [comment]
you need to build from source code unfortunately. dotnet build does not work properly yet - I'll build a self contained once that is fixed
